import typescript from "@rollup/plugin-typescript"
import commonjs from "@rollup/plugin-commonjs"
import terser from "@rollup/plugin-terser"
import * as fs from "fs"
import * as path from "path"

const pkg = JSON.parse(fs.readFileSync("package.json", "utf8"));

/**
 * The CommonJS bundle is built with `exports: "default"`, so `require()` returns the class
 * itself rather than a module namespace. A declaration file using `export default` claims
 * the opposite, and TypeScript rejects `require()` of it under node16 resolution. Emit a
 * sibling .d.cts describing the real shape, named so TypeScript pairs it with the .cjs.
 */
function commonJsDeclaration() {
  return {
    name: "commonjs-declaration",
    writeBundle(options) {
      if (options.format !== "cjs") {
        return;
      }
      const directory = path.dirname(options.file);
      const base = path.basename(pkg.typings, ".d.ts");
      const contents = [
        "// Generated by rollup.config.js — do not edit.",
        `// The CommonJS bundle sets \`module.exports\` to the class, which is what \`export =\``,
        "// describes. The ESM declaration next to this one is the source of truth for the types.",
        `import IniFileCache from "./${base}.js";`,
        `export = IniFileCache;`,
        "",
      ].join("\n");
      fs.writeFileSync(path.join(directory, `${base}.d.cts`), contents);
    },
  };
}

export default [
  {
    input: "src/iniFileCache.ts",
    external: [ 'fs', 'path', '@mdaemon/emitter' ],
    output: [
      { file: pkg.main, format: "cjs", exports: "default", name: "IniFileCache" },
      { file: pkg.module, format: "es", exports: "default", name: "IniFileCache" },
    ],
    plugins: [
      typescript(),
      commonjs(),
      terser(),
      commonJsDeclaration()
    ]
  }
]
